'use client';

import React from 'react';
import Link from 'next/link';
import { useAuth } from '../../context/AuthContext';
import { ArrowRight, ShieldCheck, Lock, FileText, Eye } from 'lucide-react';
import PublicHeader from '../../components/PublicHeader';

export default function PrivacyPage() {
  const { isAuthenticated } = useAuth();

  return (
    <div className="bg-zinc-950 text-zinc-100 min-h-screen relative overflow-x-hidden w-full font-sans antialiased">
      {/* Background SRE Grids */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#0f0f11_1px,transparent_1px),linear-gradient(to_bottom,#0f0f11_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none" />

      {/* Top fixed navbar */}
      {/* Top fixed navbar */}
      <PublicHeader />

      {/* Content Section */}
      <section className="relative px-4 md:px-8 lg:px-12 pt-28 pb-28 max-w-4xl mx-auto space-y-12">
        <div className="text-center space-y-3">
          <div className="inline-flex items-center space-x-2 bg-zinc-900/60 border border-zinc-800/85 px-2.5 py-1 rounded text-indigo-400 text-[9px] font-mono font-bold uppercase tracking-wider shadow-inner">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Telemetry Security</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight leading-tight">
            Privacy & Data Security Policy
          </h1>
          <p className="text-zinc-500 font-mono text-[10.5px]">Last Updated: June 9, 2026</p>
        </div>

        <div className="space-y-8 text-zinc-400 text-sm leading-relaxed font-sans">
          <p className="text-zinc-300">
            At QueueWatch, we take telemetry security, isolation, and privacy seriously. This policy documents how we collect, process, and safeguard the diagnostic telemetry streamed from your application queues.
          </p>

          <hr className="border-zinc-900" />

          {/* Section 1 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 font-mono">
              <Eye className="w-4 h-4 text-indigo-400" /> 1. Telemetry Data Collection
            </h2>
            <p>
              QueueWatch monitors operational events in your asynchronous workflows. The data collected by our client-side SDK is strictly limited to metadata required for operational diagnostic analysis, including:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-zinc-400">
              <li><strong className="text-zinc-300">Queue Metrics:</strong> Queue name, active worker count, stalled job counts, and completed/failed counts.</li>
              <li><strong className="text-zinc-300">Job Execution Performance:</strong> Latency metrics, retry counts, execution time boundaries, and job IDs.</li>
              <li><strong className="text-zinc-300">Error Stack Traces:</strong> Exception class names, failure messages, and stack trace logs generated by your workers.</li>
            </ul>
            <p className="text-xs bg-zinc-900/30 border border-zinc-900 p-3 rounded text-zinc-500 font-mono">
              Note: We do NOT collect credit card numbers, passwords, PII, or raw business data payloads. We recommend using payload filters or hash configurations to mask sensitive fields inside job logs.
            </p>
          </div>

          {/* Section 2 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 font-mono">
              <Lock className="w-4 h-4 text-indigo-400" /> 2. Information Security
            </h2>
            <p>
              All telemetry streamed to our event ingestion brokers is encrypted in transit using TLS 1.3 and encrypted at rest using AES-256. Database segments and job logs are isolated using logical workspace partitioning to prevent cross-tenant access.
            </p>
          </div>

          {/* Section 3 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 font-mono">
              <FileText className="w-4 h-4 text-indigo-400" /> 3. Data Retention & Access
            </h2>
            <p>
              By default, detailed job execution logs and stack traces are retained for 14 days on our standard tiers to facilitate incident triage, after which they are permanently pruned. Aggregate metrics are stored for up to 90 days. We do not sell, rent, or share your telemetry metadata with third-party advertisers.
            </p>
          </div>

          {/* Section 4 */}
          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 font-mono">
              4. Contact Us
            </h2>
            <p>
              If you have any questions regarding telemetry data isolation, security auditing, or compliance certificates, please contact our SRE operations team at <code className="text-indigo-400 bg-zinc-900/50 px-1 py-0.5 rounded font-mono text-xs">security@queuewatch.io</code>.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-zinc-900 bg-zinc-955 py-12 px-4 md:px-8 text-center text-xs text-zinc-550 font-mono">
        <p>&copy; {new Date().getFullYear()} QueueWatch. Operational Reliability Platform. All rights reserved.</p>
      </footer>
    </div>
  );
}
